### ISSUE TITLE
那些交易接口NodeQuant.node可以开源吗？

### ISSUE THREAD

**Issue by jandykwan** [zhangshuiyong/nodequant#13]
有些需要定制一些底层的功能，希望能开源。

**Comment by zhangshuiyong** [comment]
19年会做开源NodeQuant.node的工作，但是没想好用什么开源协议，开源是为了鼓励代码协作，但是我在对nodequant开源后，发现虽然有人fork了，但是极少人提交代码合并过来，这个领域好像很少开源文化，所以打击了积极性

**Comment by wi24rd** [comment]
可以考虑 LGPLv3.0+
https://ftp.gnu.org/gnu/Licenses/lgpl-3.0.txt
不过使用 GPLv3.0 甚至 AGPLv3.0
都不会影响原作者自己如何在自己的项目中使用，毕竟所有权还在作者那（但是得保证版权方是只有自己掌控或者其他所有者也同意或者直接要求贡献者签CLA处理这些事），只是会引起很多想白嫖的吐口水。

另外如果重视的话，正规的做法应该在每个源代码文件头都加上版权说明，懒得话也可以用SPDX。

On Fri, Feb 22, 2019 at 9:56 AM Tom.Cheung <notifications@github.com> wrote:
>
> 19年会做开源NodeQuant.node的工作，但是没想好用什么开源协议，开源是为了鼓励代码协作，但是我在对nodequant开源后，发现虽然有人fork了，但是极少人提交代码合并，所以打击了积极性
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
GNU powered it...
GPL protect it...
GOD blessing it...

Regards,
Wi24rd

**Comment by samael65535** [comment]
还有个原因是量化这块用node不多吧。

**Comment by QuantBull** [comment]
> 19年会做开源NodeQuant.node的工作，但是没想好用什么开源协议，开源是为了鼓励代码协作，但是我在对nodequant开源后，发现虽然有人fork了，但是极少人提交代码合并过来，这个领域好像很少开源文化，所以打击了积极性

希望能用N-API实现，解决在ctp接口没有变化的情况下适应高版本nodejs的问题，加快速度哦，看好你

**Comment by langhuihui** [comment]
我手头有一个N-API版本的，希望开源，共同进步

**Comment by QuantBull** [comment]
> 我手头有一个N-API版本的，希望开源，共同进步

兄弟，开源下一起研究哈

**Comment by QuantBull** [comment]
> 我手头有一个N-API版本的，希望开源，共同进步

好巧，兄弟你也是苏宁的？豆芽账号多少，加一下交流哈

**Comment by jandykwan** [comment]
现在做量化，数据是件麻烦事。
你们是怎么解决的？自己在网上买？




------------------ 原始邮件 ------------------
发件人: "大V"<notifications@github.com>; 
发送时间: 2019年7月29日(星期一) 凌晨0:45
收件人: "zhangshuiyong/nodequant"<nodequant@noreply.github.com>; 
抄送: "关键"<113226@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zhangshuiyong/nodequant] 那些交易接口NodeQuant.node可以开源吗？ (#13)



 
我手头有一个N-API版本的，希望开源，共同进步
  
好巧，兄弟你也是苏宁的？豆芽账号多少，加一下交流哈
 
&mdash;

**Comment by QuantBull** [comment]
> 现在做量化，数据是件麻烦事。 你们是怎么解决的？自己在网上买？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "大V"<notifications@github.com>; 发送时间: 2019年7月29日(星期一) 凌晨0:45 收件人: "zhangshuiyong/nodequant"<nodequant@noreply.github.com>; 抄送: "关键"<113226@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [zhangshuiyong/nodequant] 那些交易接口NodeQuant.node可以开源吗？ (#13) 我手头有一个N-API版本的，希望开源，共同进步 好巧，兄弟你也是苏宁的？豆芽账号多少，加一下交流哈 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

对头，网上买

**Comment by zhangshuiyong** [comment]
已开源
