### ISSUE TITLE
再一次开源建议

### ISSUE THREAD

**Issue by QuantBull** [zhangshuiyong/nodequant#14]
兄弟 读了你的代码，发觉你的js不是很熟练，引擎里的逻辑也有不少可以优化的地方，何不开源出ctp addon的源码，大家一起群策群力，共同维护好这个项目呢？我的软肋在于不会封装ctp addon，但相对精于js和交易，有10年前端经验和四年交易经验，想与你一起做这个项目，但苦于不开源核心代码，真的是不敢用。兄弟考虑考虑。

**Comment by DOVER123** [comment]
> 
> 
> 兄弟 读了你的代码，发觉你的js不是很熟练，引擎里的逻辑也有不少可以优化的地方，何不开源出ctp addon的源码，大家一起群策群力，共同维护好这个项目呢？我的软肋在于不会封装ctp addon，但相对精于js和交易，有10年前端经验和四年交易经验，想与你一起做这个项目，但苦于不开源核心代码，真的是不敢用。兄弟考虑考虑。

大佬我目前在搞前端有三年经验，搞过股票比特币玩的都不好，量化这块想入个门啥的得从哪里起步啊？

**Comment by zhangshuiyong** [comment]
哥们，你先使用吧，没啥不敢的，可以用网络工具监控一下没有把请求发到其他ip的。对应分支是能work的，nodequant ctp_6.3.15对应的期货公司的生产环境和simnow可以在线测试。（开源需要投入时间的，之前说过开源的但是太忙了）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"DOVER"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月26日(星期二) 下午3:42
收件人:&nbsp;"zhangshuiyong/nodequant"<nodequant@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangshuiyong/nodequant] 再一次开源建议 (#14)





  
兄弟 读了你的代码，发觉你的js不是很熟练，引擎里的逻辑也有不少可以优化的地方，何不开源出ctp addon的源码，大家一起群策群力，共同维护好这个项目呢？我的软肋在于不会封装ctp addon，但相对精于js和交易，有10年前端经验和四年交易经验，想与你一起做这个项目，但苦于不开源核心代码，真的是不敢用。兄弟考虑考虑。
  
大佬我目前在搞前端有三年经验，搞过股票比特币玩的都不好，量化这块想入个门啥的得从哪里起步啊？

**Comment by zhangshuiyong** [comment]
哥们，你先使用吧，没啥不敢的，可以用网络工具监控一下没有把请求发到其他ip的。对应分支是能work的，nodequant ctp_6.3.15对应的期货公司的生产环境和simnow可以在线测试。（开源需要投入时间的，之前说过开源的但是太忙了，等等迟点）




------------------ 原始邮件 ------------------
发件人:&nbsp;"DOVER"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月26日(星期二) 下午3:42
收件人:&nbsp;"zhangshuiyong/nodequant"<nodequant@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangshuiyong/nodequant] 再一次开源建议 (#14)





  
兄弟 读了你的代码，发觉你的js不是很熟练，引擎里的逻辑也有不少可以优化的地方，何不开源出ctp addon的源码，大家一起群策群力，共同维护好这个项目呢？我的软肋在于不会封装ctp addon，但相对精于js和交易，有10年前端经验和四年交易经验，想与你一起做这个项目，但苦于不开源核心代码，真的是不敢用。兄弟考虑考虑。
  
大佬我目前在搞前端有三年经验，搞过股票比特币玩的都不好，量化这块想入个门啥的得从哪里起步啊？

**Comment by QuantBull** [comment]
> > 兄弟 读了你的代码，发觉你的js不是很熟练，引擎里的逻辑也有不少可以优化的地方，何不开源出ctp addon的源码，大家一起群策群力，共同维护好这个项目呢？我的软肋在于不会封装ctp addon，但相对精于js和交易，有10年前端经验和四年交易经验，想与你一起做这个项目，但苦于不开源核心代码，真的是不敢用。兄弟考虑考虑。
> 
> 大佬我目前在搞前端有三年经验，搞过股票比特币玩的都不好，量化这块想入个门啥的得从哪里起步啊？

光有形远远不够 多修道

**Comment by zhangshuiyong** [comment]
已开源
