### ISSUE TITLE
订阅行情

### ISSUE THREAD

**Issue by liuwenhong007** [zhangshuiyong/nodequant#16]
遇到一个订阅行情，没收到推送的问题

**Comment by zhangshuiyong** [comment]
描述一下使用哪个分支

**Comment by liuwenhong007** [comment]
是node10_ctp6.3.16.64分支，目前用的api版本是6.3.19

**Comment by zhangshuiyong** [comment]
使用node10_ctp6.3.15.64，可以使用simnow测试

**Comment by liuwenhong007** [comment]
试过node10_ctp6.3.15_64了，也使用了simnow的6.3.19和6.3.15，提示：Decrypt handshake data failed，我应该怎样做呢

**Comment by liuwenhong007** [comment]
应该是我改上期提供的dll动态链库就可以登录，不过就是没有推送行情

**Comment by zhangshuiyong** [comment]
已解决
