### ISSUE TITLE
订阅行情只收到一条推送

### ISSUE THREAD

**Issue by zhurizhe** [zhangshuiyong/nodequant#19]
我用的是方正期货的接口，看穿式监管生产版本，6.3.15
https://www.founderfu.com/fzzqqh_2019/technology_407.html

可以正常登录交易端口和行情端口。
也可以正常拿到所有合约，但是不管我订阅所有合约还是只订阅一条合约，都只能收到一条推送，之后就收不到了。

如果再次订阅，又会收到一条，并不是持续不断的收到推送。

不知道哪位大佬能帮我看一下这个问题？

**Comment by zhangshuiyong** [comment]
@zhurizhe 周一到周五？

**Comment by zhurizhe** [comment]
> @zhurizhe 周一到周五？

是的，大佬，可以加你qq或者微信聊吗？

**Comment by zhangshuiyong** [comment]
@zhurizhe vx: zhangshuiyong

**Comment by zhangshuiyong** [comment]
更新了一个docker使用nodequant方式，已验证没问题，master分支的nodequant代码：https://github.com/zhangshuiyong/nodequant/blob/master/linux-run.md
