### ISSUE TITLE
CTP Client is undefine.....

### ISSUE THREAD

**Issue by zuoerlost** [zhangshuiyong/nodequant#7]
CtpClient is undefine!!!CtpClient Only Support Windows Node.js-v8.9.1-32bit/Windows Node.js-v8.9.1-64bit/Linux x64 Node.jsv8.9.1
SgitClient is undefine!!!SgitClient Only Support Windows Node.js-v8.9.1-32bit/Linux x64 Node.js-v8.9.1
>>>>>>>>>>  NodeQuant <<<<<<<<<<
Date :下午4:50:22

大佬，我是在MAC 搭建了这套环境，目前已经运行不报错了，但是启动的时候CTP Client is undefine 是因为 我的操作系统问题吗？

**Comment by zhangshuiyong** [comment]
*.so 只是unix/linux下的动态库形式， 在mac里面不支持。上期技术的CTP API暂时只有windows平台和Linux平台的动态库。你可以用docker或者虚拟机运行nodequant
