### ISSUE TITLE
出现错误来源CTP ,Msg:Market Front Response Error. ErrorId:77,ErrorMsg:undefined

### ISSUE THREAD

**Issue by futureltj** [zhangshuiyong/nodequant#9]
可以正常登陆，无法获取市场信息，报错代码77.

>>>>>>>>>>  NodeQuant <<<<<<<<<<
Date :00:52:46
2018-4-27 00:52:46,信息来源MainEngine ,Msg:MainEngine Start
CtpClient Created
2018-4-27 00:52:46,信息来源CTP ,Msg:Trade Front connected.--> The Login
docker0: Success
2018-4-27 00:52:46,信息来源CTP ,Msg:Trade Front login request sended. Return:0
2018-4-27 00:52:46,信息来源CTP ,Msg:Market Front connected. --> Then Login
docker0: Success
2018-4-27 00:52:46,信息来源CTP ,Msg:Market Front login request sended. return:0
2018-4-27 00:52:46,信息来源CTP ,Msg:CTP Trade Front login successfully
2018-4-27 00:52:46,信息来源CTP ,Msg:Trade Front confirm settlementInfo request sended. Return:0
2018-4-27 00:52:46,信息来源CTP ,Msg:Market Front login successfully
2018-4-27 00:52:46,信息来源CTP ,Msg:Trade Front confirm settlementInfo successfully. --> Then query all contracts.
2018-4-27 00:52:47,信息来源CTP ,Msg:Trade Front query all contract: Received all contracts.
2018-4-27 00:52:47,信息来源StrategyEngine ,Msg:StrategyEngine Start
2018-4-27 00:52:47,信息来源Demo ,Msg:Demo策略启动成功
出现错误来源CTP ,Msg:Market Front Response Error. ErrorId:77,ErrorMsg:undefined

**Comment by zhangshuiyong** [comment]
请试试docker 使用nodequant的入门方式：https://github.com/zhangshuiyong/nodequant/blob/master/linux-run.md
